services:
  jekyll:
    image: jekyll/jekyll
    command: jekyll serve --incremental --livereload --force_polling
    volumes:
      - .:/srv/jekyll
    ports:
      - '4000:4000'
      - '35729:35729'